name: Build Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # This adds the manual "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write # Required to allow the workflow to upload to Releases

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "demo-build"
          name: "Latest Debug Build"
          body: "This is an automated debug build from the main branch."
          files: exampleApp/build/outputs/apk/debug/exampleApp-debug.apk
          token: ${{ secrets.GITHUB_TOKEN }}
